import Head from 'next/head'
import Image from 'next/image'

import * as THREE from 'three'
import { Canvas, useFrame } from '@react-three/fiber'
import { PerspectiveCamera, OrbitControls, Environment, ContactShadows } from '@react-three/drei'
import { EffectComposer } from '@react-three/postprocessing'

import Box from '../components/Box'
import Base from '../components/Base'

export default function Home() {
  return (
    <>
      <Head>
        <title>R3F SETUP</title>
        <meta name="description" content="Generated by R3F Repo" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Canvas shadows>
          <PerspectiveCamera makeDefault fov={50} position={[0, 2.5, 15]} />
          <OrbitControls />

          <directionalLight position={[2.5, 2.5, 2.5]} castShadow />

          <Box castShadow />
          <Base />


          <Environment background castShadow>
            <mesh scale={10}>
              <sphereGeometry args={[1, 64, 33]} />
              <meshBasicMaterial color="#353535" side={THREE.BackSide} />
            </mesh>
          </Environment>

          <ContactShadows
            position={[0, -1.5, 0]}
            opacity={.5}
          />

          <EffectComposer>
          </EffectComposer>
        </Canvas>
      </main>
    </>
  )
}
